export const PROVINCES = ["Ilocos Sur", "Ilocos Norte"] as const;
export type Province = (typeof PROVINCES)[number];

export const ILOCOS_SUR_LOCATIONS: Record<string, string[]> = {
  "Alilem": ["Alilem Daya", "Amilongan", "Anaao", "Apang", "Apaya", "Batbato", "Daddaay", "Dalawa", "Kiat"],
  "Banayoyo": ["Bagbagotot", "Banbanaal", "Cabaritan", "Elefante", "Guardia", "Lintic", "Montero", "Nagyubuyuban", "Pila", "Poblacion", "Surong", "Valenzuela", "Villaluz"],
  "Bantay": ["Aggay", "An-annam", "Balaleng", "Banaoang", "Bulag", "Buquig", "Cabalangegan", "Cabaroan", "Cabuscabusan", "Capangpangan", "Guimod", "Lingsat", "Malingeb", "Mira", "Ora", "Paing", "Puspus", "Quimmarayan", "Sagneb", "Sagpat", "San Isidro", "San Julian", "San Mariano", "San Martin", "San Vicente", "Taleb", "Tay-ac"],
  "Burgos": ["Amguid", "Balingaoan", "Banay", "Bessang", "Cabaritan", "Calingayan", "Dalig", "Dallang", "Dayawen", "Dirita", "Guang-guang", "Linao", "Luna", "Lucaban", "Macaoayan", "Mambug", "Mandirig", "Nagpanaoan", "Paday", "Pagangpang", "Patar", "San Vicente", "Sardeng", "Subadi Norte", "Subadi Sur", "Taliao"],
  "Cabugao": ["Alinaay", "Aragan", "Arnap", "Baclig", "Bato", "Bonifacio", "Bungro", "Cacadiran", "Caellayan", "Carusipan", "Catucdaan", "Cuancabal", "Cuantacla", "Daclapan", "Dardarat", "Lipit", "Marcos", "Margaay", "Nagsincaoan", "Namruangan", "Pila", "Pug-os", "Quezon", "Reppaac", "Rizal", "Sabang", "Sagayaden", "Salapasap", "Salomague", "Sisam", "Turod"],
  "Candon City": ["Allangigan 1st", "Allangigan 2nd", "Amboy", "Ayudante", "Bagani Campo", "Bagani Gabor", "Bagani Macalig", "Bagani Tocgo", "Bagani Ubbog", "Bagar", "Balingaoan", "Bugarin", "Calaoa-an", "Calongbuyan", "Caterman", "Cubcubbuot", "Darapidap", "Langlangca 1st", "Langlangca 2nd", "Oaig-Daya", "Palacapac", "Paras", "Parioc 1st", "Parioc 2nd", "Patpata 1st", "Patpata 2nd", "Paypayad", "San Agustin", "San Andres", "San Antonio", "San Isidro", "San Jose", "San Juan", "San Nicolas", "San Pedro", "Santo Tomas", "Tablac", "Talogtog", "Tamurong 1st", "Tamurong 2nd", "Villarica"],
  "Caoayan": ["Anonang Mayor", "Anonang Menor", "Baggoc", "Callaguip", "Caparacadan", "Fuerte", "Don Alejandro Quirolgico", "Don Dimas Querubin", "Don Lorenzo Querubin", "Manangat", "Naguilian", "Nansuagao", "Puro", "Tamurong", "Villamar", "Don Lino Abaya", "Pantay-Quitiquit"],
  "Cervantes": ["Aluling", "Comillas North", "Comillas South", "Concepcion", "Dinwede", "Malaya", "Pilipil", "Remedios", "Rosario", "San Juan", "San Luis", "Santa Clara", "Tagudin"],
  "Galimuyod": ["Abaya", "Baracbac", "Borobor", "Buyog", "Caliao", "Calimugtong", "Guimod", "Mckinley", "Nagsingcaoan", "Oaig-Daya", "Pagangpang", "Patac", "Poblacion", "San Vicente"],
  "Gregorio del Pilar": ["Alfonso", "Bussot", "Concepcion", "Doldol", "Mabatano", "Poblacion Norte", "Poblacion Sur"],
  "Lidlidda": ["Banucal", "Bequi-Walin", "Bugui", "Calungbuyan", "Caminawit", "Carcarabasa", "Labut", "Poblacion Norte", "Poblacion Sur", "San Vicente", "Suysuyan"],
  "Magsingal": ["Alangan", "Bacar", "Bato", "Bucarot", "Cabaroan", "Camarao", "Caraisan", "Dacutan", "Labut", "Maas-asin", "Macatcatud", "Maratudo", "Miramar", "Namarabar", "Napasan", "Puro", "Purok-a-dakkel", "Purok-a-bassit", "San Basilio", "San Clemente", "San Julian", "San Lucas", "San Ramon", "San Vicente", "Santa Monica", "Sarsaracat"],
  "Narvacan": ["Abuot", "Aquib", "Banglayan", "Blockhouse", "Bulanos", "Cadacad", "Cagayungan", "Camarao", "Casilian", "Codoog", "Dasay", "Dinalaoan", "Estancia", "Lanipao", "Lungog", "Margaay", "Marozo", "Nanguneg", "Orence", "Pantoc", "Paratong", "Parparia", "Quinarayan", "Rivadavia", "San Antonio", "San Jose", "San Pablo", "San Pedro", "Santa Lucia", "Sarmingan", "Sucoc", "Sulvec", "Turod"],
  "Quirino": ["Banoen", "Cayus", "Lamag", "Legleg", "Malideg", "Namitpit", "Patiacan", "Poblacion", "Suagayan"],
  "Salcedo": ["Baybayading", "Boguisil", "Calaoa-an", "Culiong", "Dinaratan", "Kaliwakiw", "Lucbuban", "Madansong", "Maligcong", "Miliang", "Poblacion", "Sagneb", "San Gaspar", "San Juan", "San Roque", "Sibut", "Tagita"],
  "San Emilio": ["Cabaroan", "Cancio", "Lancuas", "Matindeg", "Poblacion", "San Juan", "Sibsibbu", "Tiagan"],
  "San Ildefonso": ["Arnap", "Bahet", "Beling", "Bungro", "Busiing Sur", "Busiing Norte", "Gongogong", "Iboy", "Kinamantirisan", "Otol", "Poblacion", "Pudoc", "Sagsagat", "Sagat", "Tuya-a"],
  "San Juan": ["Asilang", "Bacsil", "Baliw", "Banneng", "Bao-ing", "Barbaran", "Camangaan", "Camindoroan", "Caronoan", "Darao", "Daramuang", "Guimod Norte", "Guimod Sur", "Immayos Norte", "Immayos Sur", "Labnig", "Lapting", "Lira", "Malamin", "Muraya", "Nagsabaran", "Nagsupotan", "Pandayan", "Refaro", "Resurreccion", "Sabangan", "San Isidro", "Saoang", "Solotsolot", "Sunggiam", "Surila"],
  "San Vicente": ["Bantaoay", "Bayubay Norte", "Bayubay Sur", "Lubong", "Pudoc", "San Sebastian"],
  "Santa": ["Ampandula", "Banaoang", "Basug", "Bucalag", "Cabangaran", "Calungboyan", "Casiber", "Dammay", "Labut Norte", "Labut Sur", "Mabilbila Norte", "Mabilbila Sur", "Magsaysay District", "Manueva", "Marcos District", "Nagpanaoan", "Namalangan", "Oribi", "Pasungol", "Quezon District", "Quirino District", "Rancho", "Rizal District", "Sacuyya Norte", "Sacuyya Sur", "San Jose"],
  "Santa Catalina": ["Cabittaogan", "Cabuloan", "Calongbuyan", "Namnama", "Paratong", "Poblacion", "Pangada", "Subec", "Tamurong"],
  "Santa Cruz": ["Amarao", "Babayoan", "Bacsayan", "Banay", "Bato", "Buliclic", "Calingayan", "Capanikian", "Casilian", "Daligan", "Mambug", "Mantaya", "Poblacion", "Sagapan", "San Antonio", "San Jose", "San Pedro", "Sevilla", "Sidaoen"],
  "Santa Lucia": ["Alincaoeg", "Angkileng", "Ayaoan", "Banbanaba", "Bantoc", "Bao-as", "Barangay I", "Barangay II", "Barangay III", "Bawani", "Buliclic", "Burgos", "Cabaritan", "Catayagan", "Conconig", "Cuartel", "Damacuag", "Lubong", "Lumbang", "Marcos", "Nagtocaoc", "Namnama", "Palali", "Paratong", "Pias", "Rondalla", "Sabuanan", "San Juan", "San Pedro", "Suagayan", "Valdefuente", "Vigan"],
  "Santa Maria": ["Ag-agrao", "Ampandula", "Babangot", "Baliw Daya", "Baliw Laud", "Bia-o", "Bulbulala", "Cabaroan", "Danuman East", "Danuman West", "Donghol", "Gusing", "Laslasong Norte", "Laslasong Sur", "Laslasong West", "Lesseb", "Lingsat", "Lubong", "Macatcatud", "Maynganay Norte", "Maynganay Sur", "Nagsayaoan", "Nalidaoan", "Nutia", "Pacang", "Parioc 1st", "Parioc 2nd", "Penned", "Poblacion Norte", "Poblacion Sur", "San Alejandro", "San Gelacio", "San Pedro", "Silag", "Suso", "Tangaoan"],
  "Santiago": ["Al-alinao Norte", "Al-alinao Sur", "Ambugat", "Bayo", "Bigbiga", "Binacud", "Bucyao", "Bulbulala", "Buso-buso", "Butol", "Caburao", "Danuman East", "Danuman West", "Dinwede East", "Dinwede West", "Gabay", "Imus", "Lang-ayan", "Mambug", "Olo-olo Norte", "Olo-olo Sur", "Poblacion Norte", "Poblacion Sur", "Sabanen", "Salcedo", "San Jose", "San Roque", "San Vicente", "Ubbog"],
  "Santo Domingo": ["Binalayangan", "Borobor", "Cabigbigaan", "Cabusligan", "Calay-ab", "Camragan", "Casili", "Flora", "Lagatit", "Laoingen", "Lussoc", "Nalasin", "Nagbettedan", "Naglaoa-an", "Pangalisan", "Panay", "Pussuac", "Quimmarayan", "San Pablo", "Santa Clara", "Suksukit", "Suso", "Vacunero"],
  "Sigay": ["Abquilan", "Mabileg", "Poblacion", "San Elias"],
  "Sinait": ["Aguing", "Ballaigui", "Baracbac", "Barikir", "Battao", "Cabaritan", "Cabisilan", "Calanutian", "Calingayan", "Concepcion", "Dean Leopoldo Yabes", "Dadao", "Dadalaquiten Norte", "Dadalaquiten Sur", "Duyay-ayat", "Jordan", "Katipunan", "Macabiag", "Magsaysay", "Marnay", "Masical", "Nagbalioartian", "Nagcullooban", "Naglumpa-an", "Nagmullocan", "Namnama", "Pacis", "Paratong", "Poblacion", "Purag", "Quibit-quibit", "Quimmallogong", "Ricudo", "Sabangan", "Sallacapo", "Santa Cruz", "Sapriana", "Tapao", "Teppeng", "Tubigay", "Ubbog"],
  "Sugpon": ["Balbalayang", "Bangabanga", "Danac", "Pangotan", "Poblacion", "Uguid"],
  "Suyo": ["Baringcucurong", "Cabcaburao", "Man-atong", "Patoc-ao", "Poblacion", "Suyo Proper", "Urzadan", "Uso"],
  "Tagudin": ["Ag-aguman", "Al-alinao", "Ambalayat", "Baracbac", "Bariw", "Baroro", "Basca", "Bitalag", "Borono", "Bucao", "Cabaniguan", "Cabaroan", "Caburlaoan", "Cantoria", "Concepcion", "Dada Norte", "Dada Sur", "Del Pilar", "Farig", "Gari Norte", "Gari Sur", "Las-ud", "Lapting", "Libtong", "Lubnac", "Magsaysay", "Malacañang", "Mariposa", "Miguel", "Padua", "Pallogan", "Paratong", "Quirino", "Rizal", "Salcedo", "San Antonio", "San Isidro", "San Juan", "San Jose", "San Rafael", "San Vicente", "Sarmingan", "Tambidao", "Tampugo", "Tarangotong"],
  "Vigan City": ["Ayusan Norte", "Ayusan Sur", "Barangay I", "Barangay II", "Barangay III", "Barangay IV", "Barangay V", "Barangay VI", "Barraca", "Beddeng Laud", "Beddeng Daya", "Bongtolan", "Bulala", "Cabalangegan", "Cabaroan Daya", "Cabaroan Laud", "Camangaan", "Capangpangan", "Mindoro", "Nagsangalan", "Pantay Daya", "Pantay Fatima", "Pantay Laud", "Paoa", "Paratong", "Pong-ol", "Purok-a-bassit", "Purok-a-dakkel", "Raois", "Rugsuanan", "Salindeg", "San Jose", "San Julian Norte", "San Julian Sur", "San Pedro", "Santa Elena", "Tamag"],
};

export const ILOCOS_NORTE_LOCATIONS: Record<string, string[]> = {
  "Laoag City": [
    "Barangay No. 1, San Lorenzo",
    "Barangay No. 2, Santa Joaquina",
    "Barangay No. 3, Nuestra Señora del Rosario",
    "Barangay No. 4, San Guillermo",
    "Barangay No. 5, San Pedro",
    "Barangay No. 6, San Agustin",
    "Barangay No. 7-A, Nuestra Señora del Natividad",
    "Barangay No. 7-B, Nuestra Señora del Natividad",
    "Barangay No. 8, San Vicente",
    "Barangay No. 9, Santa Angela",
    "Barangay No. 10, San Jose",
    "Barangay No. 11, Santa Balbina",
    "Barangay No. 12, San Isidro",
    "Barangay No. 13, Nuestra Señora de Visitacion",
    "Barangay No. 14, Santo Tomas",
    "Barangay No. 15, San Guillermo",
    "Barangay No. 16, San Jacinto",
    "Barangay No. 17, San Francisco",
    "Barangay No. 18, San Quirino",
    "Barangay No. 19, Santa Marcela",
    "Barangay No. 20, San Miguel",
    "Barangay No. 21, San Pedro",
    "Barangay No. 22, San Andres",
    "Barangay No. 23, San Matias",
    "Barangay No. 24, Nuestra Señora de Consolacion",
    "Barangay No. 25, Santa Cayetana",
    "Barangay No. 26, San Marcelino",
    "Barangay No. 27, Nuestra Señora de Soledad",
    "Barangay No. 28, San Bernardo",
    "Barangay No. 29, Santo Tomas",
    "Barangay No. 30-A, Suyo",
    "Barangay No. 30-B, Santa Maria",
    "Barangay No. 31, Talingaan",
    "Barangay No. 32-A, La Paz East",
    "Barangay No. 32-B, La Paz West",
    "Barangay No. 32-C, La Paz East",
    "Barangay No. 33-A, La Paz Proper",
    "Barangay No. 33-B, La Paz Proper",
    "Barangay No. 34-A, Gabu Norte West",
    "Barangay No. 34-B, Gabu Norte East",
    "Barangay No. 35, Gabu Sur",
    "Barangay No. 36, Araniw",
    "Barangay No. 37, Calayab",
    "Barangay No. 38-A, Mangato East",
    "Barangay No. 38-B, Mangato West",
    "Barangay No. 39, Santa Rosa",
    "Barangay No. 40, Balatong",
    "Barangay No. 41, Balacad",
    "Barangay No. 42, Apaya",
    "Barangay No. 43, Cavit",
    "Barangay No. 44, Zamboanga",
    "Barangay No. 45, Tangid",
    "Barangay No. 46, Nalbo",
    "Barangay No. 47, Bengcag",
    "Barangay No. 48-A, Cabungaan North",
    "Barangay No. 48-B, Cabungaan South",
    "Barangay No. 49-A, Darayday",
    "Barangay No. 49-B, Raraburan",
    "Barangay No. 50, Buttong",
    "Barangay No. 51-A, Nangalisan East",
    "Barangay No. 51-B, Nangalisan West",
    "Barangay No. 52-A, San Mateo",
    "Barangay No. 52-B, Lataag",
    "Barangay No. 53, Rioeng",
    "Barangay No. 54-A, Camangaan",
    "Barangay No. 54-B, Lagui-Sail",
    "Barangay No. 55-A, Barit-Pandan",
    "Barangay No. 55-B, Salet-Bulangon",
    "Barangay No. 55-C, Vira",
    "Barangay No. 56-A, Bacsil North",
    "Barangay No. 56-B, Bacsil South",
    "Barangay No. 57, Pila",
    "Barangay No. 58, Casili",
    "Barangay No. 59-A, Dibua South",
    "Barangay No. 59-B, Dibua North",
    "Barangay No. 60-A, Caaoacan",
    "Barangay No. 60-B, Madiladig",
    "Barangay No. 61, Cataban",
    "Barangay No. 62-A, Navotas North",
    "Barangay No. 62-B, Navotas South",
  ],
};

export function getCitiesForProvince(province: string): string[] {
  if (province === "Ilocos Norte") return Object.keys(ILOCOS_NORTE_LOCATIONS).sort();
  if (province === "Ilocos Sur") return Object.keys(ILOCOS_SUR_LOCATIONS).sort();
  return [];
}

export function getBarangaysForCity(province: string, city: string): string[] {
  if (province === "Ilocos Norte") return ILOCOS_NORTE_LOCATIONS[city] ?? [];
  if (province === "Ilocos Sur") return ILOCOS_SUR_LOCATIONS[city] ?? [];
  return [];
}

export function isAllowedProvince(province: string): province is Province {
  return (PROVINCES as readonly string[]).includes(province);
}
